version: '3'
services:
  ionic:
    build:
      context: .
    ports:
    - "0.0.0.0:3000:3000" # ng dev server
    - "0.0.0.0:5000:5000" # node
    - "0.0.0.0:8100:8100" # ionic dev server
    - "0.0.0.0:8080:8080" # webpack
    - "0.0.0.0:9876:9876" # karma
    - "0.0.0.0:35729:35729" # livereload
    volumes:
    - "./../:/app"
#    command: "ionic serve -b -p 8100--address 0.0.0.0"
